language: haskell
ghc:
  - '8.6'
  - '8.4'
  - '8.2'
  - '8.0'
jobs:
  include:
    - stage: deploy
      if: tag =~ ^v[\d\.]+$
      script: skip
      deploy:
        provider: hackage
        username: mtth
        password:
          secure: ap8/hMzF7D9YHPdUHvK3qgxKEorQS+jO/xPaV3zgcBgqN6NTkHpSvCUBzI9n8WZe489zcTY1SkYiEh+VSy8vj+nxPTdInbS2p/tB+qYnzRNlozWveWbw9dwYBDpTOavkAe/WMeAVg5zfm76/tsxkqGcxdqPf8iIXqx0MdS7Iif15X/DDRwgxpyGS0kZoKByoxQwOdsvqx4YtO7pbSm4s+62+jrIky5AI2MMzpt0V3am0RRygQxDZIHXATpFX4Bj0RB619qrHIh7T1MRQi12vspoUC3j0XY92E+UHTNEiWXsVF4cRjPU4N6R+KjZXLBbEoqEOfHUqzee1ACcD8QVYdIAEZVYzdAM5PUIMVggsqUx3pag5dslwjJf8KFOHcddUSFDrTuB1LpTZHrcKbdsuF1WF1J1ShWm18cwArGO/JiQsuLfHMPAMFApxYKWYfAbNO1g48pw2r659rS/AMaA8EPk77LlvAPF0N7at1ba33AIprqfFVQfkxjuSKiZXf4fZoA5HruimYWLxh0JRsDrM3oHXTRhgL16WTrjmnu0+I/DrSTBdj1DFeeSYdwh88x4vLwuMO+eS6sGCj77SJgPq5E3OuNGXuU9dHjeqVQ0RnHYzO3o7uTKQ5wu04B3QKO4o5uAqwnbsMIuNTAgPHEBQ8WG/BVYvAFhByWzuO2db09c=
        on:
          repo: mtth/yx
          tags: true
